spring:
  datasource:
    url: jdbc:h2:mem:userAppIDdb
    driver-class-name: org.h2.Driver
    username: ibm
    password: ibm
  main:
    allow-bean-definition-overriding: true
    
    
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  application:
    name: loginMs
    
jwt:
  secret: secretkey123
  get:
    token:
      uri: /authenticate
   
jwt.token.validity.minuite: 30

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${eureka.uri:http://localhost:8100//eureka}          

feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000
    
    
security:
  oauth2:
    client:
      accessTokenUri: https://us-south.appid.cloud.ibm.com/oauth/v4/d45e06da-d9e7-40ee-8949-2ff63336f552/token
      userAuthorizationUri: https://us-south.appid.cloud.ibm.com/oauth/v4/d45e06da-d9e7-40ee-8949-2ff63336f552/authorization
    resource:
      userInfoUri: https://us-south.appid.cloud.ibm.com/oauth/v4/d45e06da-d9e7-40ee-8949-2ff63336f552/userinfo
    
server:
  port: 8400
